# $FreeBSD: Timothy Bourke <timbob@bigpond.com> $
# Original from: Timothy Bourke <timbob@bigpond.com>

COMMENT =	Fast open-source implementation of Standard ML

PORTNAME =	polyml
PORTVERSION =	5.5.2
PORTREVISION =	1
DISTNAME =	${PORTNAME}.${PORTVERSION}
DIST_SUBDIR =	${PORTNAME}

CATEGORIES =	lang

HOMEPAGE =	www.polyml.org

MASTER_SITES =	${MASTER_SITE_SOURCEFORGE:=polyml/}

LIB_DEPENDS =	devel/libffi

USE_LIBTOOL=		gnu
CONFIGURE_STYLE =	gnu

.include <bsd.port.mk>
